image: python:3.8

variables:
  HEROKU_APP_NAME: "dga-prod-api"
  HEROKU_API_KEY: "1d8c2daa-b379-43c0-ae70-1fd1a1e137fd"

stages:
  - build
  - test
  - deploy

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build --pull -t $HEROKU_APP_NAME -f Dockerfile .
    - docker login -u _ -p "$HEROKU_API_KEY" registry.heroku.com
    - docker tag $HEROKU_APP_NAME registry.heroku.com/$HEROKU_APP_NAME/web
    - docker push registry.heroku.com/$HEROKU_APP_NAME/web

test:
  image: python:3.8
  script:
    - pip install -r requirements.txt
    - python manage.py test

deploy:
  image: registry.heroku.com/heroku-cli:latest
  script:
    - echo "$HEROKU_API_KEY" | docker login -u _ --password-stdin registry.heroku.com
    - heroku container:push web --app $HEROKU_APP_NAME
    - heroku container:release web --app $HEROKU_APP_NAME
    - heroku run python manage.py migrate --app $HEROKU_APP_NAME
  only:
    - main
    - staging
    - Testing
    - production
