image: python:3.8

variables:
  HEROKU_APP_NAME: "dga-prod-api"
  HEROKU_API_KEY: "1d8c2daa-b379-43c0-ae70-1fd1a1e137fd"
  PASS: heroku auth:token

stages:
  - build
  - deploy
  - migrate
  
before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt


build:
  stage: build
  script:
    - python manage.py collectstatic --noinput
    - docker build -t my-image .

deploy:
  stage: deploy
  script:
    - echo "Deploying to Heroku..."
    - heroku container:login
    - heroku container:push web --app $HEROKU_APP_NAME
    - heroku container:release web --app $HEROKU_APP_NAME
  only:
    - main
    - staging
    - Testing

migrate:
  stage: migrate
  script:
    - echo "Running migrations on Heroku..."
    - heroku run python manage.py migrate --app $HEROKU_APP_NAME
  only:
    - main
    - staging
    - Testing
