image: python:3.8

variables:
  HEROKU_APP_NAME: dga-prod-api
  HEROKU_API_KEY: 1d8c2daa-b379-43c0-ae70-1fd1a1e137fd

stages:
  - test
  - deploy

# Define the test stage
test:
  # Use the official Python Docker image
  image: python:3.8
  # Set up the environment
  environment:
    name: test
  # Define the script to run
  script:
    - pip install -r requirements.txt
    - python manage.py test

# Define the deploy stage
deploy:
  # Use the official Heroku CLI Docker image
  image: registry.heroku.com/heroku-cli:latest
  # Set up the environment
  environment:
    name: production
  # Define the script to run
  script:
    - echo "$HEROKU_API_KEY" | docker login -u _ --password-stdin registry.heroku.com
    - heroku container:push web --app $HEROKU_APP_NAME
    - heroku container:release web --app $HEROKU_APP_NAME