# Generated by Django 4.1.3 on 2022-12-09 22:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('cf20c545-1e27-4f78-a791-0a9ea977df49'), editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseModelWithStatus',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packages_service.basemodel')),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('packages_service.basemodel',),
        ),
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('basemodelwithstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packages_service.basemodelwithstatus')),
                ('title', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.TextField(blank=True, null=True)),
                ('package_particulars', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('tie_to_event', models.BooleanField(default=False)),
                ('expire_after_event', models.BooleanField(default=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
            ],
            bases=('packages_service.basemodelwithstatus',),
        ),
        migrations.CreateModel(
            name='PackageTimelinesModel',
            fields=[
                ('basemodelwithstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packages_service.basemodelwithstatus')),
                ('package_from', models.DateTimeField(blank=True, null=True)),
                ('package_to', models.DateTimeField(blank=True, null=True)),
                ('no_of_days', models.IntegerField(blank=True, null=True)),
                ('no_of_nights', models.IntegerField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration', to='packages_service.packagemodel')),
            ],
            bases=('packages_service.basemodelwithstatus',),
        ),
        migrations.CreateModel(
            name='PackageReviewsModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packages_service.basemodel')),
                ('rating', models.IntegerField(default=0)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.CharField(default='Anonymous', max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='packages_service.packagemodel')),
            ],
            bases=('packages_service.basemodel',),
        ),
        migrations.CreateModel(
            name='PackageRelatedEvent',
            fields=[
                ('basemodelwithstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packages_service.basemodelwithstatus')),
                ('event_name', models.CharField(max_length=100)),
                ('event_from', models.DateTimeField(blank=True, null=True)),
                ('event_to', models.DateTimeField(blank=True, null=True)),
                ('package', models.ManyToManyField(related_name='related_events', to='packages_service.packagemodel')),
            ],
            bases=('packages_service.basemodelwithstatus',),
        ),
        migrations.CreateModel(
            name='PackageLocationModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packages_service.basemodel')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('city_town', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.CharField(blank=True, max_length=50, null=True)),
                ('lng', models.CharField(blank=True, max_length=50, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='packages_service.packagemodel')),
            ],
            bases=('packages_service.basemodel',),
        ),
        migrations.CreateModel(
            name='PackageImagesModel',
            fields=[
                ('basemodelwithstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packages_service.basemodelwithstatus')),
                ('image', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.UUIDField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages_service.packagemodel')),
            ],
            bases=('packages_service.basemodelwithstatus',),
        ),
        migrations.CreateModel(
            name='PackageCurrencyModel',
            fields=[
                ('basemodelwithstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packages_service.basemodelwithstatus')),
                ('type', models.CharField(blank=True, choices=[('PER PERSON PER DAY', 'PER PERSON PER DAY'), ('PER PERSON PER WHOLE TRIP', 'PER PERSON PER WHOLE TRIP'), ('PER GROUP', 'PER GROUP'), ('OTHER', 'OTHER')], max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='packages_service.packagemodel')),
            ],
            bases=('packages_service.basemodelwithstatus',),
        ),
        migrations.CreateModel(
            name='PackageAnalytics',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packages_service.basemodel')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='packages_service.packagemodel')),
            ],
            bases=('packages_service.basemodel',),
        ),
    ]
