# Generated by Django 4.1.3 on 2023-02-15 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCurrencyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f8c5fd82-62b9-4369-b3ce-51199aa34f03'), editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('PER PERSON PER DAY', 'PER PERSON PER DAY'), ('PER PERSON PER WHOLE TRIP', 'PER PERSON PER WHOLE TRIP'), ('PER GROUP', 'PER GROUP'), ('OTHER', 'OTHER')], max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('package_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageImagesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f8c5fd82-62b9-4369-b3ce-51199aa34f03'), editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('package_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageRemarks',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f8c5fd82-62b9-4369-b3ce-51199aa34f03'), editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('package_id', models.UUIDField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=100, null=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageReviewsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f8c5fd82-62b9-4369-b3ce-51199aa34f03'), editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.CharField(default='Anonymous', max_length=100)),
                ('package_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f8c5fd82-62b9-4369-b3ce-51199aa34f03'), editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f8c5fd82-62b9-4369-b3ce-51199aa34f03'), editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.TextField(blank=True, null=True)),
                ('package_particulars', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('tie_to_event', models.BooleanField(default=False)),
                ('expire_after_event', models.BooleanField(default=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('city_town', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.CharField(blank=True, max_length=50, null=True)),
                ('lng', models.CharField(blank=True, max_length=50, null=True)),
                ('package_from', models.DateTimeField(blank=True, null=True)),
                ('package_to', models.DateTimeField(blank=True, null=True)),
                ('no_of_days', models.IntegerField(blank=True, null=True)),
                ('no_of_nights', models.IntegerField(blank=True, null=True)),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event_from', models.DateTimeField(blank=True, null=True)),
                ('event_to', models.DateTimeField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(to='packages_service.tagsmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
