# Generated by Django 4.1.3 on 2022-12-10 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5894442-4060-4206-a5ea-5341d98b150b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
