# Generated by Django 4.1.3 on 2023-02-13 21:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0002_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('194d6923-e6b6-4513-8cf3-ca36c2aa9ede'), editable=False),
        ),
    ]
