# Generated by Django 4.1.3 on 2023-01-07 06:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0003_alter_basemodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('33d2180f-16ae-4a8a-addf-d9d69e1812b1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='packagemodel',
            name='basemodelwithstatus_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='packages_service.basemodelwithstatus'),
        ),
    ]
