# Generated by Django 4.1.3 on 2023-02-13 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0003_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('edd030c4-7f39-4242-bfbb-2891bbf5134d'), editable=False),
        ),
    ]
