# Generated by Django 4.1.3 on 2023-02-13 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0004_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('241b6b71-448d-4a27-bfdc-0ccd48636c1e'), editable=False),
        ),
    ]
