# Generated by Django 4.1.3 on 2023-02-13 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0005_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('7efbb3af-002e-4bf2-8239-eeacd61d7000'), editable=False),
        ),
    ]
