# Generated by Django 4.1.3 on 2023-01-07 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0005_remove_packagelocationmodel_basemodel_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('7d796354-fd1f-40e1-beed-327f44f7b833'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='packagemodel',
            name='reference_number',
            field=models.CharField(max_length=50),
        ),
    ]
