# Generated by Django 4.1.3 on 2023-01-12 12:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0006_alter_packagemodel_package_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packages_service.basemodel')),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('packages_service.basemodel',),
        ),
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('5a61286c-4b27-4f37-8cec-9d9412d7dca2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='packagemodel',
            name='tags',
            field=models.ManyToManyField(to='packages_service.tagsmodel'),
        ),
    ]
