# Generated by Django 4.1.3 on 2023-02-13 21:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0007_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('0cb7be87-9f07-487b-b5c3-5ab67e87ab1c'), editable=False),
        ),
    ]
