# Generated by Django 4.1.3 on 2023-01-12 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0007_tagsmodel_alter_packagemodel_package_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('98c7712e-fb0a-4324-bbdf-8d38c1a029c7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tagsmodel',
            name='tag',
            field=models.CharField(default='null', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
