# Generated by Django 4.1.3 on 2023-01-12 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0008_alter_packagemodel_package_id_alter_tagsmodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('76b8964c-6045-4545-8894-1fa841250561'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tagsmodel',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
