# Generated by Django 4.1.3 on 2023-01-24 14:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0009_alter_packagemodel_package_id_alter_tagsmodel_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRemarks',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packages_service.basemodel')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('package_id', models.UUIDField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=100, null=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
            ],
            bases=('packages_service.basemodel',),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('c8ea1059-27c6-4c3a-b701-25aaaed3f1d1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
