# Generated by Django 4.1.3 on 2023-02-13 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0009_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('67cc1301-b10e-4e8b-8cc9-badba3dcf617'), editable=False),
        ),
    ]
