# Generated by Django 4.1.3 on 2023-02-13 21:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0013_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('9ad5580e-2bf8-4a23-bf29-f883c30463ae'), editable=False),
        ),
    ]
