# Generated by Django 4.1.3 on 2023-02-13 23:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0014_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('79182628-a444-4b77-bf19-9c7bba4b6d2e'), editable=False),
        ),
    ]
