# Generated by Django 4.1.3 on 2023-02-13 23:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0015_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('5d57af5d-f1df-4f3a-9937-41954cd0bda5'), editable=False),
        ),
    ]
