# Generated by Django 4.1.3 on 2023-02-13 23:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0016_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('4157d87b-0191-4965-bf08-a0b25aa7f916'), editable=False),
        ),
    ]
