# Generated by Django 4.1.3 on 2023-02-13 23:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0017_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('abd0e381-0ebc-4a53-93d4-2345ef05e1df'), editable=False),
        ),
    ]
