# Generated by Django 4.1.3 on 2023-02-14 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0019_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('eb3588d4-d8e3-40fe-adbb-b3c65e8b3bdd'), editable=False),
        ),
    ]
