# Generated by Django 4.1.3 on 2023-02-14 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0020_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('435007be-a685-4134-a0e0-f8aac3a3e691'), editable=False),
        ),
    ]
