# Generated by Django 4.1.3 on 2023-02-14 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0021_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('54dc5220-afbd-4696-a647-9e46ecfb1291'), editable=False),
        ),
    ]
