# Generated by Django 4.1.3 on 2023-02-14 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0022_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('ffb342de-b44b-4e24-a596-473280126cc7'), editable=False),
        ),
    ]
