# Generated by Django 4.1.3 on 2023-02-14 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0023_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('56fa8702-4216-43e8-ae3d-dc1615b9cd23'), editable=False),
        ),
    ]
