# Generated by Django 4.1.3 on 2023-02-14 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages_service', '0024_alter_packagemodel_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='package_id',
            field=models.UUIDField(default=uuid.UUID('ccf3f504-b728-4b67-9f2d-222ff08f76b0'), editable=False),
        ),
    ]
