# Generated by Django 4.0 on 2022-10-29 07:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='email',
            field=models.EmailField(default='example_email@gmail.com', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('49d11161-677d-495f-ad61-ecc2428d2efc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
