# Generated by Django 4.1.3 on 2023-02-15 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abcf7dba-ce25-4fe8-bac4-26cb6e45962f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organizationaccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abcf7dba-ce25-4fe8-bac4-26cb6e45962f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abcf7dba-ce25-4fe8-bac4-26cb6e45962f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professionalaccountsmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abcf7dba-ce25-4fe8-bac4-26cb6e45962f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professionalupgradesmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abcf7dba-ce25-4fe8-bac4-26cb6e45962f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicuseraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abcf7dba-ce25-4fe8-bac4-26cb6e45962f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='residentialaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abcf7dba-ce25-4fe8-bac4-26cb6e45962f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rolesmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abcf7dba-ce25-4fe8-bac4-26cb6e45962f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffuseraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abcf7dba-ce25-4fe8-bac4-26cb6e45962f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abcf7dba-ce25-4fe8-bac4-26cb6e45962f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
