# Generated by Django 4.0 on 2022-10-29 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_usermodel_email_baseusermodel_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseusermodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('633d2f7c-2af9-4cca-a4da-74fe22507064'), primary_key=True, serialize=False),
        ),
    ]
