# Generated by Django 4.0 on 2022-10-29 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_baseusermodel_username_alter_basemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d7205e98-dc80-4e0f-93a4-e2c98bad73e2'), primary_key=True, serialize=False),
        ),
    ]
