# Generated by Django 3.2.7 on 2022-10-29 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_basemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c4a29613-aed0-4e34-9395-ffeb092da0a6'), primary_key=True, serialize=False),
        ),
    ]
