# Generated by Django 4.1.3 on 2023-02-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_departmentmodel_rolesmodel_is_department_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='name',
            field=models.CharField(default='Executive', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
