# Generated by Django 3.2.7 on 2022-10-29 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_basemodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationaccount',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='publicuseraccount',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='staffuseraccount',
            name='user_type',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('PUBLIC USER', 'PUBLIC USER'), ('INTERNAL STAFF', 'INTERNAL STAFF'), ('ORGANIZATION', 'ORGANIZATION')], default='PUBLIC USER', max_length=25),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e31e9c3e-aeb9-43bb-99f3-f966f2e83311'), primary_key=True, serialize=False),
        ),
    ]
