# Generated by Django 4.1.3 on 2023-02-15 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_rolesmodel_user_staffuseraccount_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicuseraccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffuseraccount',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='staffuseraccount',
            name='user',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolesmodel',
            name='is_primary_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='department_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_general_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='roles',
            field=models.ManyToManyField(related_name='user_roles', to='authapp.rolesmodel'),
        ),
        migrations.AlterField(
            model_name='residentialaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolesmodel',
            name='role',
            field=models.CharField(blank=True, choices=[('BOOKING MANAGER', 'BOOKING MANAGER'), ('FINANCE OFFICER', 'FINANCE OFFICER'), ('CUSTOMER CARE', 'CUSTOMER CARE'), ('ICT OFFICER', 'ICT OFFICER'), ('BOOKING OFFICER', 'BOOKING OFFICER'), ('GENERAL MANAGER', 'GENERAL MANAGER'), ('DIRECTOR', 'DIRECTOR'), ('GENERAL STAFF', 'GENERAL STAFF'), ('CEO', 'CEO')], max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='OrganizationAccount',
        ),
        migrations.DeleteModel(
            name='PublicUserAccount',
        ),
        migrations.DeleteModel(
            name='StaffUserAccount',
        ),
    ]
