# Generated by Django 3.2.7 on 2022-10-29 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_basemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bfd45438-38ad-4514-9c72-9c7e0b8988c8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
