# Generated by Django 4.1.3 on 2023-02-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_rolesmodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesmodel',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
