# Generated by Django 3.2.7 on 2022-10-29 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_basemodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolesmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='rolesmodel',
            name='basemodelwithstatus_ptr',
            field=models.OneToOneField(auto_created=True, default=uuid.UUID('e2b99630-5fe4-446b-8736-70ec7b73cc0d'), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authapp.basemodelwithstatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e2b99630-5fe4-446b-8736-70ec7b73cc0d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organizationaccount',
            name='industry',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationaccount',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
