# Generated by Django 4.1.3 on 2022-12-09 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20221029_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalAccountsModel',
            fields=[
                ('basemodelwithstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authapp.basemodelwithstatus')),
                ('account_name', models.CharField(max_length=50, unique=True)),
            ],
            bases=('authapp.basemodelwithstatus',),
        ),
        migrations.RenameField(
            model_name='otpverification',
            old_name='status',
            new_name='verified',
        ),
        migrations.RemoveField(
            model_name='residentialaddress',
            name='id',
        ),
        migrations.AddField(
            model_name='residentialaddress',
            name='basemodelwithstatus_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authapp.basemodelwithstatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e4c8c24-5e35-4aa9-9640-cccceee12312'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rolesmodel',
            name='role',
            field=models.CharField(choices=[('BOOKING MANAGER', 'BOOKING MANAGER'), ('FINANCE OFFICER', 'FINANCE OFFICER'), ('CUSTOMER CARE', 'CUSTOMER CARE'), ('ICT OFFICER', 'ICT OFFICER'), ('BOOKING OFFICER', 'BOOKING OFFICER'), ('GENERAL MANAGER', 'GENERAL MANAGER'), ('DIRECTOR', 'DIRECTOR'), ('GENERAL STAFF', 'GENERAL STAFF'), ('SUPER USER', 'SUPER USER'), ('CEO', 'CEO')], default='GENERAL STAFF', max_length=25),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('PUBLIC USER', 'PUBLIC USER'), ('INTERNAL STAFF', 'INTERNAL STAFF'), ('ORGANIZATION', 'ORGANIZATION'), ('PROFESSIONAL', 'PROFESSSIONAL')], default='PUBLIC USER', max_length=25),
        ),
        migrations.CreateModel(
            name='ProfessionalUpgradesModel',
            fields=[
                ('basemodelwithstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authapp.basemodelwithstatus')),
                ('upgraded_by', models.CharField(blank=True, max_length=50, null=True)),
                ('professional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_accounts', to='authapp.professionalaccountsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_upgrade', to='authapp.usermodel')),
            ],
            bases=('authapp.basemodelwithstatus',),
        ),
        migrations.AddField(
            model_name='professionalaccountsmodel',
            name='account_roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='authapp.rolesmodel'),
        ),
    ]
