# Generated by Django 4.1.3 on 2023-02-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_rolesmodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
