# Generated by Django 4.1.3 on 2022-12-09 22:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_professionalaccountsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64c18fe0-3935-4c62-9049-6a32c5cd7518'), editable=False, primary_key=True, serialize=False),
        ),
    ]
