# Generated by Django 4.1.3 on 2022-12-10 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_basemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('578f24c2-584c-4254-a739-1ac067fbd01e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
