# Generated by Django 4.1.3 on 2023-01-07 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_basemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e99ceb44-effb-4a87-a37f-6f08b01e83fd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
