# Generated by Django 4.1.3 on 2023-01-07 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_alter_basemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8da69200-9cd8-45c0-b24a-beb477c87a75'), editable=False, primary_key=True, serialize=False),
        ),
    ]
