# Generated by Django 4.1.3 on 2023-01-07 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_alter_basemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb0431dd-7ea4-4bc7-93ab-206a78f58b0d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
