# Generated by Django 4.1.3 on 2023-01-07 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_alter_basemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bfbdea6d-1c72-41fb-bae9-1849d8759dba'), editable=False, primary_key=True, serialize=False),
        ),
    ]
