# Generated by Django 4.1.3 on 2023-01-12 12:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_alter_basemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc92e25c-a228-4ce8-abcc-5df3613b072c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
