# Generated by Django 4.1.3 on 2023-01-12 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_alter_basemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a2a94c1d-7c77-44a0-ae96-4525b3c02115'), editable=False, primary_key=True, serialize=False),
        ),
    ]
