# Generated by Django 4.1.3 on 2023-01-12 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_alter_basemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c55b5bed-c30b-45be-8bf1-8fbd6845b0e5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
