# Generated by Django 4.1.3 on 2023-01-24 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_alter_basemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b9eb5ec8-3f0c-4119-b035-270f93622c81'), editable=False, primary_key=True, serialize=False),
        ),
    ]
