
USER_TYPES = [
    ('PUBLIC USER', 'PUBLIC USER'),
    ('INTERNAL STAFF', 'INTERNAL STAFF'),
    ('ORGANIZATION', 'ORGANIZATION'),
    ('PROFESSIONAL', 'PROFESSSIONAL')
]

ROLES = [
    ("BOOKING MANAGER", "BOOKING MANAGER"),
    ("FINANCE OFFICER", "FINANCE OFFICER"),
    ("CUSTOMER CARE", "CUSTOMER CARE"),
    ("ICT OFFICER", "ICT OFFICER"),
    ("BOOKING OFFICER", "BOOKING OFFICER"),
    ("GENERAL MANAGER", "GENERAL MANAGER"),
    ("DIRECTOR", "DIRECTOR"),
    ("GENERAL STAFF", "GENERAL STAFF"),
    ("SUPER USER", "SUPER USER"),
    ("CEO", "CEO")
]

PROFESSIONAL_ACCOUNTS = [
    ("DRIVER", "DRIVER"),
    ("TRANSLATOR", "TRANSLATOR"),
    ("TOUR GUIDE", "TOUR GUIDE"),
    ("CONSULTANT", "CONSULTANT")
]

INDUSTRY_TYPES = [
    ("HOSPITALITY", "HOSPITALITY"),
    ("TRAVEL AND TOURS", "TRAVEL AND TOURS"),
    ("TRANSPORTATION", "TRANSPORTATION")
]